stages:
- stage: AutoApply
  pool: P-UKS-LIN
  dependsOn: Plan
  condition: and(not(failed()), not(canceled()), eq(dependencies.Plan.outputs['Evaluate.OPAVariable.AutoApproveShouldRun'], 'true'))
  jobs:

  # Apply Jobs
  - template: ../Jobs/auto_apply.yml