stages:
- stage: Integration
  condition: and(or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual')), ne(variables['System.PullRequest.TargetBranch'], 'refs/heads/main'))
  pool: P-UKS-LIN
  jobs:
  
  # Integration Test Jobs
  - template: ../Jobs/integration.yml